export const idlePrompts: string[] = [
  'Create a TypeScript interface for a user profile',
  'Explain CSS flexbox for centering a div',
  'A python script to parse a CSV file',
  'Write a git commit message for a new feature',
  'Generate a REST API endpoint in Node.js with Express',
  'A regex to validate an international phone number',
  'Explain the concept of closures in JavaScript',
  'Write a C# function to find the factorial of a number',
  'How to set up a basic CI/CD pipeline with GitHub Actions',
  'Create a boilerplate HTML5 file structure',
  'Optimize a slow SQL query for a `products` table',
  'A Dockerfile for a simple Python Flask application',
  'Explain the difference between `let`, `const`, and `var`',
  'Write a Java function to sort an array of integers',
  'Generate a color palette for a modern web application',
  'A shell script to backup a directory',
  'How to handle asynchronous operations in Rust',
  'Create a simple React component for a button',
  'Explain the SOLID principles with code examples',
  'Write a unit test for a login function using Jest',
  'A Go function to read a file from disk',
  'How to use CSS Grid for a responsive photo gallery',
  'Generate a Kubernetes deployment YAML for a web server',
  'A Swift function to format a date object',
  'Refactor a nested `if` statement for better readability',
  'Explain the purpose of a virtual environment in Python',
  'Create a basic serverless function on AWS Lambda',
  'A TypeScript type for a complex nested API response',
  'How to implement authentication using JWT',
  'Write a CSS animation for a loading spinner'
];
