import { TechStack } from '../types';

export const categorizedTechStacks: Record<string, TechStack[]> = {
  'Frontend': [
    { id: 'react', name: 'React', logo: '⚛️' },
    { id: 'vue', name: 'Vue.js', logo: '🟢' },
    { id: 'angular', name: 'Angular', logo: '🅰️' },
    { id: 'svelte', name: 'Svelte', logo: '🟠' },
    { id: 'nextjs', name: 'Next.js', logo: '⚫' },
    { id: 'remix', name: 'Remix', logo: '💿' },
    { id: 'astro', name: 'Astro', logo: '🚀' },
    { id: 'solidjs', name: 'SolidJS', logo: '🧱' },
  ],
  'Backend': [
    { id: 'node', name: 'Node.js', logo: '📦' },
    { id: 'express', name: 'Express.js', logo: '🛤️' },
    { id: 'django', name: 'Django', logo: '🎸' },
    { id: 'flask', name: 'Flask', logo: '⚗️' },
    { id: 'fastapi', name: 'FastAPI', logo: '⚡' },
    { id: 'springboot', name: 'Spring Boot', logo: '🌱' },
    { id: 'ruby_on_rails', name: 'Ruby on Rails', logo: '💎' },
    { id: 'laravel', name: 'Laravel', logo: '💧' },
  ],
  'Languages': [
    { id: 'javascript', name: 'JavaScript', logo: '🟡' },
    { id: 'typescript', name: 'TypeScript', logo: '🔷' },
    { id: 'python', name: 'Python', logo: '🐍' },
    { id: 'go', name: 'Go', logo: '🐹' },
    { id: 'rust', name: 'Rust', logo: '🦀' },
    { id: 'java', name: 'Java', logo: '☕' },
    { id: 'csharp', name: 'C#', logo: '#️⃣' },
    { id: 'php', name: 'PHP', logo: '🐘' },
  ],
  'Databases': [
    { id: 'postgresql', name: 'PostgreSQL', logo: '🐘' },
    { id: 'mysql', name: 'MySQL', logo: '🐬' },
    { id: 'mongodb', name: 'MongoDB', logo: '🍃' },
    { id: 'redis', name: 'Redis', logo: '🔺' },
    { id: 'sqlite', name: 'SQLite', logo: '🪶' },
    { id: 'firebase', name: 'Firebase', logo: '🔥' },
  ],
  'Cloud & DevOps': [
    { id: 'docker', name: 'Docker', logo: '🐳' },
    { id: 'kubernetes', name: 'Kubernetes', logo: '☸️' },
    { id: 'aws', name: 'AWS', logo: '☁️' },
    { id: 'gcp', name: 'GCP', logo: '🌥️' },
    { id: 'azure', name: 'Azure', logo: '🌐' },
    { id: 'terraform', name: 'Terraform', logo: '🏗️' },
    { id: 'github_actions', name: 'GitHub Actions', logo: '🤖' },
    { id: 'vercel', name: 'Vercel', logo: '▲' },
  ],
  'Architecture Patterns': [
    { id: 'microservices', name: 'Microservices', logo: '🧩' },
    { id: 'event_driven', name: 'Event-Driven', logo: '📬' },
    { id: 'serverless', name: 'Serverless', logo: '🕊️' },
    { id: 'monolithic', name: 'Monolithic', logo: '🏛️' },
    { id: 'cqrs', name: 'CQRS', logo: '↔️' },
  ],
  'CI/CD Tools': [
    { id: 'jenkins', name: 'Jenkins', logo: '🤵' },
    { id: 'gitlab_ci', name: 'GitLab CI', logo: '🦊' },
    { id: 'circleci', name: 'CircleCI', logo: '🔵' },
    { id: 'travisci', name: 'Travis CI', logo: '🚦' },
  ],
  'CSS Frameworks': [
    { id: 'tailwindcss', name: 'Tailwind CSS', logo: '💨' },
    { id: 'bootstrap', name: 'Bootstrap', logo: '🅱️' },
    { id: 'sass', name: 'Sass', logo: '🎨' },
    { id: 'materialui', name: 'Material-UI', logo: 'Ⓜ️' },
    { id: 'chakraui', name: 'Chakra UI', logo: '⚡️' },
  ],
  'Testing': [
    { id: 'jest', name: 'Jest', logo: '🃏' },
    { id: 'vitest', name: 'Vitest', logo: '🧪' },
    { id: 'cypress', name: 'Cypress', logo: '🌲' },
    { id: 'playwright', name: 'Playwright', logo: '🎭' },
    { id: 'storybook', name: 'Storybook', logo: '📚' },
  ],
  'Mobile': [
      { id: 'react_native', name: 'React Native', logo: '📱' },
      { id: 'flutter', name: 'Flutter', logo: '🐦' },
      { id: 'swift', name: 'Swift', logo: '🦅' },
      { id: 'kotlin', name: 'Kotlin', logo: '🤖' },
  ],
};
